# Generated by Django 5.2.5 on 2025-08-14 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_prompt', models.TextField()),
                ('short_story', models.TextField(blank=True)),
                ('character_description', models.TextField(blank=True)),
                ('background_description', models.TextField(blank=True)),
                ('character_image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('combined_image', models.ImageField(blank=True, null=True, upload_to='combined/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
